export const data = [
  {
    id: 1,
    title: "Asana",
    logoUrl: "/logos/Asana_logo.svg",
    darkLogoUrl: "/logos/Asana_logo_dark.svg",
  },
  {
    id: 2,
    title: "callhippo",
    logoUrl: "/logos/callhippo.svg",
    darkLogoUrl: "/logos/callhippo_dark.svg",
  },
  {
    id: 3,
    title: "Google_Sheets_Logo",
    logoUrl: "/logos/Google_Sheets_Logo.svg",
    darkLogoUrl: "/logos/Google_Sheets_Logo.svg",
  },
  {
    id: 4,
    title: "hubspot",
    logoUrl: "/logos/hubspot.svg",
    darkLogoUrl: "/logos/hubspot_dark.svg",
  },
  {
    id: 5,
    title: "google drive",
    logoUrl: "/logos/icons8-google-drive.svg",
    darkLogoUrl: "/logos/icons8-google-drive.svg",
  },
  {
    id: 6,
    title: "intercom",
    logoUrl: "/logos/intercom-2.svg",
    darkLogoUrl: "/logos/intercom-2.svg",
  },
  {
    id: 7,
    title: "LeadSquare",
    logoUrl: "/logos/leadsquare.png",
    darkLogoUrl: "/logos/leadsquare.png",
  },
  {
    id: 8,
    title: "Microsoft Temas",
    logoUrl: "/logos/Microsoft_Office_Teams.svg",
    darkLogoUrl: "/logos/Microsoft_Office_Teams.svg",
  },
  {
    id: 9,
    title: "Monday",
    logoUrl: "/logos/Monday_logo.svg",
    darkLogoUrl: "/logos/Monday_logo_dark.svg",
  },
  {
    id: 10,
    title: "notion",
    logoUrl: "/logos/notion-logo-svgrepo-com.svg",
    darkLogoUrl: "/logos/notion_dark.svg",
  },
  {
    id: 11,
    title: "Gmail",
    logoUrl: "/logos/official-gmail-icon-2020-.svg",
    darkLogoUrl: "/logos/official-gmail-icon-2020-.svg",
  },
  {
    id: 12,
    title: "pandadoc",
    logoUrl: "/logos/pandadoc-ar21.svg",
    darkLogoUrl: "/logos/PandaDoc_dark.svg",
  },
  {
    id: 13,
    title: "Pipedrive",
    logoUrl: "/logos/Pipedrive_Logo.svg",
    darkLogoUrl: "/logos/Pipedrive_dark.svg",
  },
  {
    id: 14,
    title: "salesforce",
    logoUrl: "/logos/salesforce-2.svg",
    darkLogoUrl: "/logos/salesforce-2.svg",
  },
  {
    id: 15,
    title: "slack-new",
    logoUrl: "/logos/slack-new-logo.svg",
    darkLogoUrl: "/logos/slack-new-logo.svg",
  },
  {
    id: 16,
    title: "sugarcrm",
    logoUrl: "/logos/sugarcrm-logo-blk.svg",
    darkLogoUrl: "/logos/sugarcrm-logo-blk_dark.svg",
  },
  {
    id: 17,
    title: "Trello",
    logoUrl: "/logos/Trello_logo.svg",
    darkLogoUrl: "/logos/Trello_logo.svg",
  },
  {
    id: 18,
    title: "WhatsApp",
    logoUrl: "/logos/WhatsApp.svg",
    darkLogoUrl: "/logos/WhatsApp.svg",
  },
  {
    id: 19,
    title: "zapier",
    logoUrl: "/logos/zapier-2.svg",
    darkLogoUrl: "/logos/zapier-2_dark.svg",
  },
  {
    id: 20,
    title: "Zendesk",
    logoUrl: "/logos/zendesk-1.svg",
    darkLogoUrl: "/logos/zendesk-1_dark.svg",
  },
  {
    id: 21,
    title: "ZoHo",
    logoUrl: "/logos/ZOHO.svg",
    darkLogoUrl: "/logos/ZOHO.svg",
  },
  {
    id: 22,
    title: "zoom-app",
    logoUrl: "/logos/zoom-app.svg",
    darkLogoUrl: "/logos/zoom-app.svg",
  },
];
